CREATE TABLE IF NOT EXISTS `keywords` (
	`iKeywordID` INT NOT NULL AUTO_INCREMENT,
	`cPage` VARCHAR(50) NOT NULL,
	`iItem` INT NOT NULL DEFAULT 0,
	`cKeywords` TEXT NOT NULL,
	PRIMARY KEY(`iKeywordID`)
) ENGINE = MyISAM;