CREATE TABLE IF NOT EXISTS `twitter` (
	`iUserID` INT NOT NULL,
	`username` VARCHAR(32) DEFAULT NULL,
	`state` SMALLINT DEFAULT 0,
	`token` VARCHAR(64) DEFAULT NULL,
	`secret` VARCHAR(64) DEFAULT NULL,
	`description` VARCHAR(255) DEFAULT NULL,
	`status` VARCHAR(140) DEFAULT NULL,
	`location` VARCHAR(80) DEFAULT NULL,
	`followers` SMALLINT DEFAULT 0,
	`mtime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`iUserID`)
);